kubernetes:
  host: https://kubernetes.default

helloworld:
  namespace: default
  image:
    name: localhost:5000/openopm-hello-world
    tag: latest
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress